name: Greetings

on: [push, pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@master
      - run: sudo rm -rf /usr/local /opt/ && mkdir -p /usr/local/{bin,share,lib64}
      - uses: lhotari/action-upterm@v1
      
